## 05_import_gsea_pipeline_outputs_brca.R
##
## Purpose:
##   Import standardized GSEAPreranked outputs generated by:
##
##     GSEA-Pipeline/preranked/scripts/02_standardize_gsea_outputs.R
##
##   These are NOT raw GSEA reports. They are OmicsKit-ready TSV files with
##   standardized lowercase/snake_case columns.
##
## Expected input directory:
##
##   inst/extdata/brca/gsea_outputs/
##
## Expected files:
##
##   GSEA_ERpositive_vs_ERnegative_Hallmark.tsv
##   GSEA_ERpositive_vs_ERnegative_GO_BP.tsv
##   GSEA_Tumor_vs_Normal_Hallmark.tsv
##   GSEA_Tumor_vs_Normal_GO_BP.tsv
##   GSEA_BRCA_all_comparisons_Hallmark_GO_BP.tsv
##
## Output package data:
##
##   data/brca_gsea_er_pos_vs_er_neg_hallmark.rda
##   data/brca_gsea_er_pos_vs_er_neg_go_bp.rda
##   data/brca_gsea_tumor_vs_normal_hallmark.rda
##   data/brca_gsea_tumor_vs_normal_go_bp.rda
##   data/brca_gsea_all_comparisons_hallmark_go_bp.rda
##   data/brca_gsea_pipeline_metadata.rda
##
## Also writes validated copies to:
##
##   inst/extdata/brca/intermediate/

options(stringsAsFactors = FALSE)

project_file <- function(...) {
  if (requireNamespace("here", quietly = TRUE)) {
    here::here(...)
  } else {
    file.path(...)
  }
}

if (!requireNamespace("data.table", quietly = TRUE)) {
  stop("Package 'data.table' is required.", call. = FALSE)
}

if (!requireNamespace("usethis", quietly = TRUE)) {
  stop("Package 'usethis' is required.", call. = FALSE)
}

library(data.table)

gsea_dir <- project_file("inst", "extdata", "brca", "gsea_outputs")
intermediate_dir <- project_file("inst", "extdata", "brca", "intermediate")

dir.create(intermediate_dir, recursive = TRUE, showWarnings = FALSE)

if (!dir.exists(gsea_dir)) {
  stop(
    "GSEA output directory does not exist: ",
    normalizePath(gsea_dir, mustWork = FALSE),
    call. = FALSE
  )
}

input_files <- list(
  brca_gsea_er_pos_vs_er_neg_hallmark = file.path(
    gsea_dir,
    "GSEA_ERpositive_vs_ERnegative_Hallmark.tsv"
  ),
  brca_gsea_er_pos_vs_er_neg_go_bp = file.path(
    gsea_dir,
    "GSEA_ERpositive_vs_ERnegative_GO_BP.tsv"
  ),
  brca_gsea_tumor_vs_normal_hallmark = file.path(
    gsea_dir,
    "GSEA_Tumor_vs_Normal_Hallmark.tsv"
  ),
  brca_gsea_tumor_vs_normal_go_bp = file.path(
    gsea_dir,
    "GSEA_Tumor_vs_Normal_GO_BP.tsv"
  ),
  brca_gsea_all_comparisons_hallmark_go_bp = file.path(
    gsea_dir,
    "GSEA_BRCA_all_comparisons_Hallmark_GO_BP.tsv"
  )
)

required_columns <- c(
  "pathway",
  "collection",
  "comparison",
  "method",
  "source",
  "rank_metric",
  "ES",
  "NES",
  "pvalue",
  "padj",
  "FWER",
  "size",
  "direction",
  "significant_fdr_0_25",
  "significant_fdr_0_05"
)

optional_columns <- c(
  "output_label",
  "report_side",
  "source_file",
  "rank_at_max",
  "leading_edge",
  "core_enrichment"
)

normalize_standardized_gsea <- function(x, file_label) {
  missing_required <- setdiff(required_columns, names(x))

  if (length(missing_required) > 0) {
    stop(
      "Missing required standardized GSEA columns in ", file_label, ":\n- ",
      paste(missing_required, collapse = "\n- "),
      "\nObserved columns:\n- ",
      paste(names(x), collapse = "\n- "),
      call. = FALSE
    )
  }

  ## Keep required + recognized optional columns. This avoids failing if the
  ## upstream GSEA-Pipeline later adds harmless annotation columns.
  keep_cols <- intersect(c(required_columns, optional_columns), names(x))
  x <- x[, ..keep_cols]

  ## Type normalization.
  char_cols <- intersect(
    c(
      "pathway",
      "collection",
      "comparison",
      "method",
      "source",
      "rank_metric",
      "direction",
      "output_label",
      "report_side",
      "source_file",
      "leading_edge",
      "core_enrichment"
    ),
    names(x)
  )

  for (cc in char_cols) {
    x[[cc]] <- as.character(x[[cc]])
  }

  numeric_cols <- intersect(
    c("ES", "NES", "pvalue", "padj", "FWER", "rank_at_max"),
    names(x)
  )

  for (nc in numeric_cols) {
    x[[nc]] <- suppressWarnings(as.numeric(x[[nc]]))
  }

  integer_cols <- intersect(c("size"), names(x))

  for (ic in integer_cols) {
    x[[ic]] <- suppressWarnings(as.integer(x[[ic]]))
  }

  logical_cols <- intersect(
    c("significant_fdr_0_25", "significant_fdr_0_05"),
    names(x)
  )

  for (lc in logical_cols) {
    if (!is.logical(x[[lc]])) {
      x[[lc]] <- as.character(x[[lc]])
      x[[lc]] <- x[[lc]] %in% c("TRUE", "True", "true", "1", "yes", "YES")
    }
  }

  ## Defensive recomputation in case upstream flags were written as strings or
  ## were affected by formatting.
  x[, significant_fdr_0_25 := !is.na(padj) & padj < 0.25]
  x[, significant_fdr_0_05 := !is.na(padj) & padj < 0.05]

  x[, direction := ifelse(NES > 0, "positive", "negative")]

  ## Basic validity checks.
  if (any(is.na(x$pathway) | x$pathway == "")) {
    stop("Empty pathway names found in ", file_label, call. = FALSE)
  }

  if (any(is.na(x$NES))) {
    warning("Some NES values are NA in ", file_label, call. = FALSE)
  }

  if (any(is.na(x$padj))) {
    warning("Some padj values are NA in ", file_label, call. = FALSE)
  }

  x[, abs_NES := abs(NES)]
  data.table::setorder(x, comparison, collection, padj, -abs_NES, pathway)
  x[, abs_NES := NULL]

  x[]
}

read_standardized_file <- function(path, object_name) {
  if (!file.exists(path)) {
    stop(
      "Expected standardized GSEA file not found for ",
      object_name,
      ":\n",
      normalizePath(path, mustWork = FALSE),
      call. = FALSE
    )
  }

  message("Reading standardized GSEA output: ", path)

  x <- data.table::fread(path)

  x <- normalize_standardized_gsea(
    x = x,
    file_label = basename(path)
  )

  x[, omicskit_object := object_name]

  x
}

objects <- list()

for (object_name in names(input_files)) {
  objects[[object_name]] <- read_standardized_file(
    path = input_files[[object_name]],
    object_name = object_name
  )
}

brca_gsea_er_pos_vs_er_neg_hallmark <- objects$brca_gsea_er_pos_vs_er_neg_hallmark
brca_gsea_er_pos_vs_er_neg_go_bp <- objects$brca_gsea_er_pos_vs_er_neg_go_bp
brca_gsea_tumor_vs_normal_hallmark <- objects$brca_gsea_tumor_vs_normal_hallmark
brca_gsea_tumor_vs_normal_go_bp <- objects$brca_gsea_tumor_vs_normal_go_bp

## Prefer the upstream merged file if present, but validate it just like the
## per-comparison files.
brca_gsea_all_comparisons_hallmark_go_bp <-
  objects$brca_gsea_all_comparisons_hallmark_go_bp

## Ensure merged file is consistent with the four individual files.
merged_from_parts <- data.table::rbindlist(
  list(
    brca_gsea_er_pos_vs_er_neg_hallmark,
    brca_gsea_er_pos_vs_er_neg_go_bp,
    brca_gsea_tumor_vs_normal_hallmark,
    brca_gsea_tumor_vs_normal_go_bp
  ),
  fill = TRUE
)

## Remove helper object labels before comparing row counts, because the upstream
## merged file may have a different object label.
expected_rows <- nrow(merged_from_parts)
observed_rows <- nrow(brca_gsea_all_comparisons_hallmark_go_bp)

if (!identical(expected_rows, observed_rows)) {
  warning(
    "Merged GSEA file row count differs from merged individual files. ",
    "Observed merged rows: ", observed_rows,
    "; expected from parts: ", expected_rows,
    ". The imported merged object will still use the upstream merged file.",
    call. = FALSE
  )
}

## Lightweight metadata object for provenance.
brca_gsea_pipeline_metadata <- data.table::data.table(
  dataset = "TCGA-BRCA",
  workflow = "GSEAPreranked",
  source_pipeline = "GSEA-Pipeline/preranked",
  input_dir = normalizePath(gsea_dir, mustWork = FALSE),
  imported_files = basename(unlist(input_files)),
  imported_objects = names(input_files),
  n_rows = vapply(objects, nrow, integer(1)),
  created = as.character(Sys.time())
)

## Write validated intermediate copies.
write_validated_copy <- function(x, file_name) {
  out_path <- file.path(intermediate_dir, file_name)
  data.table::fwrite(x, out_path, sep = "\t", quote = FALSE)
  message("Wrote validated GSEA copy: ", out_path)
}

write_validated_copy(
  brca_gsea_er_pos_vs_er_neg_hallmark,
  "GSEA_validated_ERpositive_vs_ERnegative_Hallmark.tsv"
)

write_validated_copy(
  brca_gsea_er_pos_vs_er_neg_go_bp,
  "GSEA_validated_ERpositive_vs_ERnegative_GO_BP.tsv"
)

write_validated_copy(
  brca_gsea_tumor_vs_normal_hallmark,
  "GSEA_validated_Tumor_vs_Normal_Hallmark.tsv"
)

write_validated_copy(
  brca_gsea_tumor_vs_normal_go_bp,
  "GSEA_validated_Tumor_vs_Normal_GO_BP.tsv"
)

write_validated_copy(
  brca_gsea_all_comparisons_hallmark_go_bp,
  "GSEA_validated_BRCA_all_comparisons_Hallmark_GO_BP.tsv"
)

## Save package data.
usethis::use_data(
  brca_gsea_er_pos_vs_er_neg_hallmark,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_gsea_er_pos_vs_er_neg_go_bp,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_gsea_tumor_vs_normal_hallmark,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_gsea_tumor_vs_normal_go_bp,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_gsea_all_comparisons_hallmark_go_bp,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_gsea_pipeline_metadata,
  compress = "xz",
  overwrite = TRUE
)

message("Saved BRCA standardized GSEAPreranked package objects to data/.")
message("Imported rows:")
print(brca_gsea_pipeline_metadata[, .(imported_objects, n_rows)])
