## 06_prepare_pathway_objects_brca.R
##
## Purpose:
##   Build compact BRCA pathway-analysis objects for OmicsKit vignettes from:
##
##   1) standardized GSEAPreranked imports generated by:
##        data-raw/brca/05_import_gsea_pipeline_outputs_brca.R
##
##   2) MSigDB GMT files stored in:
##        inst/extdata/brca/gsea_outputs/gmt/
##
##   3) ranked gene lists stored in:
##        inst/extdata/brca/gsea_outputs/rnk/
##
## This version fixes pathway-to-GMT matching by preserving and normalizing
## pathway names from GMT files. It is aligned with the vignette workflow:
##
##   list_gmts() / GMT gene sets
##   getgenesPA()
##   addgenesPA()
##   pathway clustering

options(stringsAsFactors = FALSE)

project_file <- function(...) {
  if (requireNamespace("here", quietly = TRUE)) {
    here::here(...)
  } else {
    file.path(...)
  }
}

require_package <- function(package, why = NULL) {
  if (!requireNamespace(package, quietly = TRUE)) {
    stop(
      "Package '", package, "' is required",
      if (!is.null(why)) paste0(" ", why),
      ".",
      call. = FALSE
    )
  }
  invisible(TRUE)
}

require_file <- function(path, label) {
  if (!file.exists(path)) {
    stop(
      "Required file is missing: ", label, "\n",
      "Expected location: ", normalizePath(path, mustWork = FALSE),
      call. = FALSE
    )
  }
  invisible(path)
}

require_dir <- function(path, label) {
  if (!dir.exists(path)) {
    stop(
      "Required directory is missing: ", label, "\n",
      "Expected location: ", normalizePath(path, mustWork = FALSE),
      call. = FALSE
    )
  }
  invisible(path)
}

require_package("data.table")
require_package("usethis", "to save pathway example objects")

library(data.table)

## -------------------------------------------------------------------------
## Name normalization
## -------------------------------------------------------------------------

normalize_pathway_name <- function(x) {
  x <- as.character(x)
  x <- trimws(x)
  x <- gsub("[[:space:]]+", "_", x)
  x <- gsub("-", "_", x)
  toupper(x)
}

## -------------------------------------------------------------------------
## Paths
## -------------------------------------------------------------------------

gsea_outputs_dir <- project_file("inst", "extdata", "brca", "gsea_outputs")
gmt_dir <- file.path(gsea_outputs_dir, "gmt")
rnk_dir <- file.path(gsea_outputs_dir, "rnk")
intermediate_dir <- project_file("inst", "extdata", "brca", "intermediate")

## Friendly fallback for a common typo in local folder names.
if (!dir.exists(gmt_dir)) {
  typo_gmt_dir <- project_file("inst", "extdata", "brca", "gsea_outpus", "gmt")
  if (dir.exists(typo_gmt_dir)) {
    warning(
      "Using typo fallback directory: ",
      typo_gmt_dir,
      "\nConsider renaming it to: ",
      gmt_dir,
      call. = FALSE
    )
    gmt_dir <- typo_gmt_dir
  }
}

require_dir(gsea_outputs_dir, "inst/extdata/brca/gsea_outputs/")
require_dir(gmt_dir, "inst/extdata/brca/gsea_outputs/gmt/")
require_dir(rnk_dir, "inst/extdata/brca/gsea_outputs/rnk/")

dir.create(intermediate_dir, recursive = TRUE, showWarnings = FALSE)

## -------------------------------------------------------------------------
## Load imported standardized GSEA objects from script 05
## -------------------------------------------------------------------------

required_rda <- c(
  "data/brca_gsea_er_pos_vs_er_neg_hallmark.rda",
  "data/brca_gsea_er_pos_vs_er_neg_go_bp.rda",
  "data/brca_gsea_tumor_vs_normal_hallmark.rda",
  "data/brca_gsea_tumor_vs_normal_go_bp.rda"
)

missing_rda <- required_rda[!file.exists(required_rda)]

if (length(missing_rda) > 0) {
  stop(
    "Required imported GSEA .rda files are missing:\n- ",
    paste(missing_rda, collapse = "\n- "),
    "\nRun first:\n",
    "source('data-raw/brca/05_import_gsea_pipeline_outputs_brca.R')",
    call. = FALSE
  )
}

load("data/brca_gsea_er_pos_vs_er_neg_hallmark.rda")
load("data/brca_gsea_er_pos_vs_er_neg_go_bp.rda")
load("data/brca_gsea_tumor_vs_normal_hallmark.rda")
load("data/brca_gsea_tumor_vs_normal_go_bp.rda")

## -------------------------------------------------------------------------
## Read GMT files
## -------------------------------------------------------------------------

read_gmt_file <- function(path) {
  lines <- readLines(path, warn = FALSE)
  lines <- lines[nzchar(trimws(lines))]

  parsed <- strsplit(lines, "\t", fixed = TRUE)

  pathway_names <- vapply(parsed, `[[`, character(1), 1)
  pathway_keys <- normalize_pathway_name(pathway_names)

  gene_sets <- lapply(parsed, function(parts) {
    genes <- parts[-c(1, 2)]
    genes <- toupper(trimws(genes))
    genes <- genes[nzchar(genes)]
    unique(genes)
  })

  names(gene_sets) <- pathway_keys

  ## If duplicated after normalization, keep the first.
  gene_sets <- gene_sets[!duplicated(names(gene_sets))]
  gene_sets[lengths(gene_sets) > 0]
}

infer_collection_from_gmt <- function(path) {
  file <- basename(path)

  if (grepl("^h\\.all\\.", file, ignore.case = TRUE)) {
    return("Hallmark")
  }

  if (grepl("^c5\\.go\\.bp\\.", file, ignore.case = TRUE)) {
    return("GO_BP")
  }

  tools::file_path_sans_ext(file)
}

gmt_files <- list.files(
  gmt_dir,
  pattern = "\\.gmt$",
  full.names = TRUE
)

if (length(gmt_files) == 0) {
  stop(
    "No GMT files were found in: ",
    normalizePath(gmt_dir, mustWork = FALSE),
    call. = FALSE
  )
}

brca_geneset_list_by_collection <- list()

for (gmt_file in gmt_files) {
  collection <- infer_collection_from_gmt(gmt_file)
  brca_geneset_list_by_collection[[collection]] <- read_gmt_file(gmt_file)
}

## Preserve pathway names from each GMT list.
## Do NOT use unlist(..., use.names = FALSE), because that removes gene-set names
## and makes pathway matching impossible.
brca_geneset_list <- list()

for (collection in names(brca_geneset_list_by_collection)) {
  current <- brca_geneset_list_by_collection[[collection]]
  for (nm in names(current)) {
    if (is.null(brca_geneset_list[[nm]])) {
      brca_geneset_list[[nm]] <- current[[nm]]
    }
  }
}

if (length(brca_geneset_list) < 3) {
  stop(
    "At least three gene sets are required after reading GMT files. Observed: ",
    length(brca_geneset_list),
    call. = FALSE
  )
}

message("Loaded GMT gene sets: ", length(brca_geneset_list))
message("Example GMT names: ", paste(head(names(brca_geneset_list), 5), collapse = ", "))

## -------------------------------------------------------------------------
## Read RNK files
## -------------------------------------------------------------------------

read_rnk <- function(path) {
  require_file(path, basename(path))

  x <- data.table::fread(
    path,
    header = FALSE,
    col.names = c("gene", "score")
  )

  x[, gene := toupper(trimws(as.character(gene)))]
  x[, score := suppressWarnings(as.numeric(score))]
  x <- x[!is.na(gene) & gene != "" & is.finite(score)]

  if (nrow(x) == 0) {
    stop("RNK file has no valid rows: ", path, call. = FALSE)
  }

  setorder(x, -score, gene)

  scores <- x$score
  names(scores) <- x$gene

  scores
}

rnk_files <- list(
  ERpositive_vs_ERnegative = file.path(
    rnk_dir,
    "BRCA_ERpositive_vs_ERnegative.rnk"
  ),
  Tumor_vs_Normal = file.path(
    rnk_dir,
    "BRCA_Tumor_vs_Normal.rnk"
  )
)

brca_ranked_gene_scores <- lapply(rnk_files, read_rnk)
brca_ranked_genes <- lapply(brca_ranked_gene_scores, names)

## -------------------------------------------------------------------------
## Validate standardized imported GSEA tables
## -------------------------------------------------------------------------

required_columns <- c(
  "pathway",
  "collection",
  "comparison",
  "ES",
  "NES",
  "pvalue",
  "padj",
  "FWER",
  "size",
  "direction"
)

optional_columns <- c(
  "method",
  "source",
  "rank_metric",
  "report_side",
  "rank_at_max",
  "leading_edge",
  "core_enrichment",
  "output_label",
  "source_file",
  "significant_fdr_0_25",
  "significant_fdr_0_05"
)

validate_standardized_gsea <- function(x, object_name) {
  missing_cols <- setdiff(required_columns, names(x))

  if (length(missing_cols) > 0) {
    stop(
      "Missing required standardized columns in ",
      object_name,
      ":\n- ",
      paste(missing_cols, collapse = "\n- "),
      call. = FALSE
    )
  }

  invisible(TRUE)
}

validate_standardized_gsea(
  brca_gsea_er_pos_vs_er_neg_hallmark,
  "brca_gsea_er_pos_vs_er_neg_hallmark"
)

validate_standardized_gsea(
  brca_gsea_er_pos_vs_er_neg_go_bp,
  "brca_gsea_er_pos_vs_er_neg_go_bp"
)

validate_standardized_gsea(
  brca_gsea_tumor_vs_normal_hallmark,
  "brca_gsea_tumor_vs_normal_hallmark"
)

validate_standardized_gsea(
  brca_gsea_tumor_vs_normal_go_bp,
  "brca_gsea_tumor_vs_normal_go_bp"
)

## -------------------------------------------------------------------------
## Convert standardized schema to OmicsKit PA-compatible schema
## -------------------------------------------------------------------------

extract_leading_edge_metric <- function(x, key) {
  x <- as.character(x)

  out <- rep(NA_real_, length(x))
  ok <- !is.na(x) & nzchar(trimws(x))

  if (!any(ok)) {
    return(out)
  }

  pattern <- paste0("(?i)", key, "\\s*=\\s*([0-9.]+)\\s*%?")
  m <- regexec(pattern, x[ok], perl = TRUE)
  hits <- regmatches(x[ok], m)

  vals <- vapply(
    hits,
    function(z) {
      if (length(z) >= 2) {
        suppressWarnings(as.numeric(z[2]))
      } else {
        NA_real_
      }
    },
    numeric(1)
  )

  out[ok] <- vals
  out
}

make_pa_table <- function(x) {
  keep <- intersect(c(required_columns, optional_columns), names(x))
  x <- copy(x[, ..keep])

  if (!"leading_edge" %in% names(x)) {
    x[, leading_edge := NA_character_]
  }

  if (!"rank_at_max" %in% names(x)) {
    x[, rank_at_max := NA_real_]
  }

  ## Compatibility columns expected by OmicsKit pathway helpers.
  x[, NAME := pathway]
  x[, NAME_KEY := normalize_pathway_name(pathway)]
  x[, COLLECTION := collection]
  x[, COMPARISON := comparison]
  x[, SIZE := as.integer(size)]
  x[, `NOM p-val` := as.numeric(pvalue)]
  x[, FDR := as.numeric(padj)]
  x[, `FDR q-val` := as.numeric(padj)]
  x[, `FWER p-val` := as.numeric(FWER)]
  x[, `RANK AT MAX` := suppressWarnings(as.numeric(rank_at_max))]
  x[, `LEADING EDGE` := as.character(leading_edge)]
  x[, Log10FDR := -log10(pmax(FDR, .Machine$double.xmin))]

  ## Parse GSEA leading-edge summary string:
  ## "tags=34%, list=12%, signal=30%"
  x[, tags := extract_leading_edge_metric(`LEADING EDGE`, "tags")]
  x[, `list` := extract_leading_edge_metric(`LEADING EDGE`, "list")]
  x[, signal := extract_leading_edge_metric(`LEADING EDGE`, "signal")]

  ## Add a stable identifier used for clustering/network examples.
  x[, PA_ID := paste(COMPARISON, COLLECTION, NAME_KEY, sep = "::")]

  x[, abs_NES := abs(NES)]
  setorder(x, COMPARISON, COLLECTION, FDR, -abs_NES, NAME)
  x[, abs_NES := NULL]

  x[]
}

brca_gsea_tumor_vs_normal_hallmark_go <- rbindlist(
  list(
    make_pa_table(brca_gsea_tumor_vs_normal_hallmark),
    make_pa_table(brca_gsea_tumor_vs_normal_go_bp)
  ),
  fill = TRUE
)

brca_gsea_er_pos_vs_er_neg_hallmark_go <- rbindlist(
  list(
    make_pa_table(brca_gsea_er_pos_vs_er_neg_hallmark),
    make_pa_table(brca_gsea_er_pos_vs_er_neg_go_bp)
  ),
  fill = TRUE
)

brca_pa_merged <- rbindlist(
  list(
    brca_gsea_tumor_vs_normal_hallmark_go,
    brca_gsea_er_pos_vs_er_neg_hallmark_go
  ),
  fill = TRUE
)

brca_pa_merged[, abs_NES := abs(NES)]
setorder(brca_pa_merged, COMPARISON, COLLECTION, FDR, -abs_NES, NAME)
brca_pa_merged[, abs_NES := NULL]

brca_pa_results <- copy(brca_pa_merged)
brca_pathway_results_merged <- copy(brca_pa_merged)

message("Merged pathway rows: ", nrow(brca_pa_merged))
message("Example PA names: ", paste(head(brca_pa_merged$NAME_KEY, 5), collapse = ", "))
message(
  "Pathways matching GMT names: ",
  sum(unique(brca_pa_merged$NAME_KEY) %in% names(brca_geneset_list)),
  " / ",
  length(unique(brca_pa_merged$NAME_KEY))
)

## -------------------------------------------------------------------------
## Build clustering gene sets from GMT memberships
## -------------------------------------------------------------------------

source(project_file("R", "doclust_PA.R"))

make_clustering_geneset_list <- function(pa_data, geneset_list) {
  keys <- pa_data$PA_ID

  out <- vector("list", length(keys))
  names(out) <- keys

  for (i in seq_along(keys)) {
    pathway_key <- pa_data$NAME_KEY[[i]]

    genes <- geneset_list[[pathway_key]]

    if (is.null(genes)) {
      genes <- character()
    }

    out[[i]] <- unique(genes)
  }

  out <- out[lengths(out) > 0]
  out
}

cluster_threshold <- 0.05

clustering_input <- brca_pa_merged[
  !is.na(FDR) & FDR < cluster_threshold
]

if (nrow(clustering_input) < 3) {
  message(
    "Fewer than three pathways with FDR < 0.05. ",
    "Using FDR < 0.25 for the example clustering object."
  )

  cluster_threshold <- 0.25

  clustering_input <- brca_pa_merged[
    !is.na(FDR) & FDR < cluster_threshold
  ]
}

if (nrow(clustering_input) < 3) {
  stop(
    "At least three significant pathways are required for clustering. ",
    "Observed with FDR < ", cluster_threshold, ": ",
    nrow(clustering_input),
    call. = FALSE
  )
}

brca_clustering_geneset_list <- make_clustering_geneset_list(
  pa_data = clustering_input,
  geneset_list = brca_geneset_list
)

if (length(brca_clustering_geneset_list) < 3) {
  unmatched <- setdiff(unique(clustering_input$NAME_KEY), names(brca_geneset_list))

  stop(
    "At least three clustering gene sets with GMT memberships are required. ",
    "Observed: ", length(brca_clustering_geneset_list), "\n",
    "This usually means pathway names in the PA table do not match GMT names.\n",
    "First unmatched PA names:\n- ",
    paste(head(unmatched, 20), collapse = "\n- "),
    "\nFirst GMT names:\n- ",
    paste(head(names(brca_geneset_list), 20), collapse = "\n- "),
    call. = FALSE
  )
}

clustering_results <- data.frame(
  GeneSet = names(brca_clustering_geneset_list),
  FDR = clustering_input$FDR[
    match(
      names(brca_clustering_geneset_list),
      clustering_input$PA_ID
    )
  ],
  stringsAsFactors = FALSE
)

brca_pa_similarity <- geneset_similarity(
  geneset_list = brca_clustering_geneset_list,
  results = clustering_results,
  fdr_th = cluster_threshold
)

brca_pa_clustering <- do_clust(brca_pa_similarity)

if ("heatmap" %in% names(brca_pa_clustering)) {
  brca_pa_clustering$heatmap <- NULL
}

## -------------------------------------------------------------------------
## Metadata
## -------------------------------------------------------------------------

brca_pa_pathway_metadata <- data.table(
  dataset = "TCGA-BRCA",
  workflow = "GSEAPreranked",
  source_pipeline = "GSEA-Pipeline/preranked",
  gmt_dir = normalizePath(gmt_dir, mustWork = FALSE),
  rnk_dir = normalizePath(rnk_dir, mustWork = FALSE),
  gmt_files = paste(basename(gmt_files), collapse = ";"),
  n_gene_sets_total = length(brca_geneset_list),
  n_ranked_er_pos_vs_er_neg = length(brca_ranked_genes$ERpositive_vs_ERnegative),
  n_ranked_tumor_vs_normal = length(brca_ranked_genes$Tumor_vs_Normal),
  n_pathway_rows = nrow(brca_pa_merged),
  n_pathway_names_matching_gmt = sum(unique(brca_pa_merged$NAME_KEY) %in% names(brca_geneset_list)),
  clustering_fdr_threshold = cluster_threshold,
  n_clustering_pathways = length(brca_clustering_geneset_list),
  created = as.character(Sys.time())
)

## -------------------------------------------------------------------------
## Save compact TSV copies
## -------------------------------------------------------------------------

fwrite(
  brca_gsea_tumor_vs_normal_hallmark_go,
  file.path(
    intermediate_dir,
    "brca_gsea_tumor_vs_normal_hallmark_go.tsv"
  ),
  sep = "\t"
)

fwrite(
  brca_gsea_er_pos_vs_er_neg_hallmark_go,
  file.path(
    intermediate_dir,
    "brca_gsea_er_pos_vs_er_neg_hallmark_go.tsv"
  ),
  sep = "\t"
)

fwrite(
  brca_pa_merged,
  file.path(
    intermediate_dir,
    "brca_pa_merged.tsv"
  ),
  sep = "\t"
)

## -------------------------------------------------------------------------
## Save package objects
## -------------------------------------------------------------------------

usethis::use_data(
  brca_gsea_tumor_vs_normal_hallmark_go,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_gsea_er_pos_vs_er_neg_hallmark_go,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_pa_merged,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_pa_results,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_pathway_results_merged,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_geneset_list,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_geneset_list_by_collection,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_ranked_genes,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_ranked_gene_scores,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_pa_similarity,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_pa_clustering,
  compress = "xz",
  overwrite = TRUE
)

usethis::use_data(
  brca_pa_pathway_metadata,
  compress = "xz",
  overwrite = TRUE
)

message("Saved BRCA pathway-analysis example objects to data/.")
message("Wrote compact pathway TSV copies to inst/extdata/brca/intermediate/.")

message("Summary:")
message("  GMT files: ", paste(basename(gmt_files), collapse = ", "))
message("  total GMT gene sets: ", length(brca_geneset_list))
message("  merged pathway rows: ", nrow(brca_pa_merged))
message("  clustering FDR threshold: ", cluster_threshold)
message("  clustering gene sets: ", length(brca_clustering_geneset_list))
