# TCGA-BRCA example datasets
#
# This file documents the TCGA-BRCA example data objects used by OmicsKit.
# The objects are generated from scripts under data-raw/brca/ and are saved
# under data/ as package data.
#
# Do not add @export to dataset documentation blocks. Roxygen2 will create
# data topics from the quoted object names.

#' TCGA-BRCA metadata
#'
#' A data frame with TCGA-BRCA clinical and sample-level metadata used across OmicsKit examples.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_metadata"

#' TCGA-BRCA RNA-seq DEA: ER-positive versus ER-negative
#'
#' A data frame of RNA-seq differential-expression results comparing ER-positive and ER-negative primary tumor samples.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rna_dea_er_pos_vs_er_neg"

#' TCGA-BRCA RNA-seq DEA: tumor versus normal
#'
#' A data frame of RNA-seq differential-expression results comparing tumor and normal samples.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rna_dea_tumor_vs_normal"

#' TCGA-BRCA RNA expression matrix for ER comparison
#'
#' A filtered RNA-seq expression matrix used for ER-positive versus ER-negative examples.
#'
#' @format A numeric matrix with features in rows and samples in columns.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rna_expr_er_shared_filtered"

#' TCGA-BRCA RNA expression matrix for tumor-normal comparison
#'
#' A filtered RNA-seq expression matrix used for tumor versus normal examples.
#'
#' @format A numeric matrix with features in rows and samples in columns.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rna_expr_tumor_normal_filtered"

#' TCGA-BRCA RNA metadata for ER comparison
#'
#' A data frame with sample annotations aligned to the ER comparison RNA-seq expression matrix.
#'
#' @format A numeric matrix with features in rows and samples in columns.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rna_metadata_er_shared"

#' TCGA-BRCA RNA metadata for tumor-normal comparison
#'
#' A data frame with sample annotations aligned to the tumor-normal RNA-seq expression matrix.
#'
#' @format A numeric matrix with features in rows and samples in columns.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rna_metadata_tumor_normal"

#' Small TCGA-BRCA transformed RNA expression matrix
#'
#' A compact transformed RNA expression matrix for visualization examples such as PCA, UMAP, t-SNE, and VSB plots.
#'
#' @format A numeric matrix with features in rows and samples in columns.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rna_vst_or_logexpr_small"

#' TCGA-BRCA RPPA feature-level DEA
#'
#' A data frame of RPPA feature-level differential-abundance results comparing ER-positive and ER-negative samples.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rppa_dea_feature_er_pos_vs_er_neg"

#' TCGA-BRCA RPPA gene-level DEA
#'
#' A data frame of RPPA gene-level differential-abundance results comparing ER-positive and ER-negative samples.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rppa_dea_gene_er_pos_vs_er_neg"

#' TCGA-BRCA RPPA feature-level expression matrix
#'
#' A filtered RPPA feature-level matrix aligned to ER comparison samples.
#'
#' @format A numeric matrix with features in rows and samples in columns.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rppa_expr_feature_er_shared"

#' TCGA-BRCA RPPA gene-level expression matrix
#'
#' A filtered RPPA gene-level matrix aligned to ER comparison samples.
#'
#' @format A numeric matrix with features in rows and samples in columns.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rppa_expr_gene_er_shared"

#' TCGA-BRCA RPPA feature map
#'
#' A data frame mapping RPPA antibody/features to curated gene-level identifiers.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_rppa_feature_map"

#' TCGA-BRCA RNA-RPPA concordance results
#'
#' A data frame with cross-layer concordance statistics between RNA-seq and RPPA for the ER comparison.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_concordance_rna_rppa_er"

#' TCGA-BRCA RNA-RPPA cross-layer correlations
#'
#' A data frame with RNA-RPPA cross-layer correlation results across shared samples and genes.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_crosslayercorr_rna_rppa_er"

#' TCGA-BRCA GSEAPreranked Hallmark: ER-positive versus ER-negative
#'
#' A standardized GSEAPreranked Hallmark result table for the ER-positive versus ER-negative comparison.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_gsea_er_pos_vs_er_neg_hallmark"

#' TCGA-BRCA GSEAPreranked GO BP: ER-positive versus ER-negative
#'
#' A standardized GSEAPreranked GO Biological Process result table for the ER-positive versus ER-negative comparison.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_gsea_er_pos_vs_er_neg_go_bp"

#' TCGA-BRCA GSEAPreranked Hallmark: tumor versus normal
#'
#' A standardized GSEAPreranked Hallmark result table for the tumor versus normal comparison.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_gsea_tumor_vs_normal_hallmark"

#' TCGA-BRCA GSEAPreranked GO BP: tumor versus normal
#'
#' A standardized GSEAPreranked GO Biological Process result table for the tumor versus normal comparison.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_gsea_tumor_vs_normal_go_bp"

#' Merged TCGA-BRCA GSEAPreranked results
#'
#' A merged standardized GSEAPreranked result table across Hallmark and GO BP collections and both BRCA comparisons.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_gsea_all_comparisons_hallmark_go_bp"

#' TCGA-BRCA GSEA pipeline metadata
#'
#' A data frame describing provenance for the imported GSEA-Pipeline preranked outputs.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_gsea_pipeline_metadata"

#' TCGA-BRCA PA object: tumor versus normal
#'
#' A compact pathway-analysis table combining Hallmark and GO BP results for tumor versus normal.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_gsea_tumor_vs_normal_hallmark_go"

#' TCGA-BRCA PA object: ER-positive versus ER-negative
#'
#' A compact pathway-analysis table combining Hallmark and GO BP results for ER-positive versus ER-negative.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_gsea_er_pos_vs_er_neg_hallmark_go"

#' Merged TCGA-BRCA pathway-analysis results
#'
#' A compact pathway-analysis table combining all BRCA comparisons and collections in an OmicsKit-compatible schema.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_pa_merged"

#' TCGA-BRCA pathway-analysis results
#'
#' A pathway-analysis result table used in OmicsKit pathway plotting, gene retrieval, and annotation examples.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_pa_results"

#' Merged TCGA-BRCA pathway results
#'
#' A merged pathway-analysis result table used as an example object for OmicsKit pathway workflows.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_pathway_results_merged"

#' TCGA-BRCA MSigDB gene-set list
#'
#' A named list of MSigDB gene sets read from GMT files used in the BRCA GSEAPreranked workflow.
#'
#' @format A named list.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_geneset_list"

#' TCGA-BRCA MSigDB gene-set list by collection
#'
#' A named list separating BRCA gene sets by MSigDB collection, including Hallmark and GO Biological Process.
#'
#' @format A named list.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_geneset_list_by_collection"

#' TCGA-BRCA ranked gene symbols
#'
#' A named list of ranked gene-symbol vectors for BRCA GSEAPreranked comparisons.
#'
#' @format A named list.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_ranked_genes"

#' TCGA-BRCA ranked gene scores
#'
#' A named list of ranked numeric gene-score vectors for BRCA GSEAPreranked comparisons.
#'
#' @format A named list.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_ranked_gene_scores"

#' TCGA-BRCA pathway similarity object
#'
#' A pathway similarity object created from real GMT memberships for BRCA pathway clustering examples.
#'
#' @format A package data object.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_pa_similarity"

#' TCGA-BRCA pathway clustering object
#'
#' A compact clustering object generated from the BRCA pathway similarity matrix.
#'
#' @format A numeric matrix with features in rows and samples in columns.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_pa_clustering"

#' TCGA-BRCA pathway object metadata
#'
#' A data frame describing provenance and dimensions of BRCA pathway-analysis objects.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_pa_pathway_metadata"

#' TCGA-BRCA clinical modeling dataset
#'
#' A clinical-only data frame prepared for Cox, GLM, ROC, and forest plot examples.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_clinical_modeling_data"

#' TCGA-BRCA univariable Cox results
#'
#' A data frame of univariable Cox model results based on clinical predictors.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_cox_univariable_clinical"

#' TCGA-BRCA adjusted Cox results
#'
#' A data frame of adjusted Cox model results based on retained clinical predictors.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_cox_adjusted_clinical"

#' TCGA-BRCA clinical GLM results
#'
#' A fitted or summarized clinical GLM object for stage-classification examples.
#'
#' @format A package data object.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_glm_stage_clinical"

#' TCGA-BRCA clinical ROC object
#'
#' A ROC object or table derived from the clinical GLM stage-classification workflow.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_roc_stage_clinical"

#' TCGA-BRCA clinical PFI level summary
#'
#' A data frame summarizing clinical predictor levels for progression-free interval modeling.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_clinical_level_summary_pfi"

#' TCGA-BRCA clinical reference template
#'
#' A data frame template describing reference levels used in clinical modeling examples.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_clinical_ref_template"

#' TCGA-BRCA GLM training data
#'
#' A training dataset used for clinical GLM stage-classification examples.
#'
#' @format A package data object.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_glm_stage_train"

#' TCGA-BRCA GLM test data
#'
#' A test dataset used for clinical GLM stage-classification examples.
#'
#' @format A package data object.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_glm_stage_test"

#' TCGA-BRCA GLM stage predictions
#'
#' A data frame of predicted probabilities or classes from the clinical GLM workflow.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_glm_stage_predictions"

#' TCGA-BRCA clinical modeling log
#'
#' A data frame recording retained and dropped variables and diagnostics from the clinical modeling workflow.
#'
#' @format A data frame.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_clinical_modeling_log"

#' TCGA-BRCA omics-layer figure provenance
#'
#' A list describing the real pre-rendered multi-omics genome-track and circos figures for sample TCGA-A1-A0SH-01.
#'
#' @format A named list.
#'
#' @source TCGA-BRCA example data processed by OmicsKit scripts under
#'   `data-raw/brca/`. External pathway results were generated by the
#'   GSEA-Pipeline preranked workflow and imported into OmicsKit.
#'
#' @keywords datasets
#'
"brca_omics_layer_tracks"

