# =============================================================================
# plotclust_PA.R
# Pathway Analysis — Gene set network visualization.
#
# Functions:
#   network_clust    — Network plots using igraph base R graphics
#   network_clust_gg — Network plots using ggraph / ggplot2 (returns objects)
# =============================================================================

########################
# Function network_clust #
########################

#' Gene set network clustering with igraph base R graphics
#'
#' Builds a weighted gene set network from a Jaccard similarity matrix, applies
#' Louvain community detection, and draws up to four network visualizations
#' using base R igraph graphics directly to the active graphics device.
#' Optionally overlays super-term community labels generated by
#' [get_superterm()].
#'
#' For a ggplot2-based version that returns plot objects instead of drawing
#' them, see [network_clust_gg()].
#'
#' @param x A `JaccardResult` object (output of [calc_jaccard()]).
#' @param clust_result A list returned by [do_clust()], used to color nodes by
#'   hierarchical cluster assignment.
#' @param jaccard_threshold Numeric. Minimum Jaccard similarity required for an
#'   edge to be included in the network. Default: `0.50`.
#' @param min_degree Integer. Minimum node degree for a node to be retained in
#'   the network. Default: `2`.
#' @param superterms Logical. If `TRUE`, overlays super-term labels at community
#'   centroids on the relevant plots. Requires `superterm_data`. Default:
#'   `FALSE`.
#' @param superterm_data A list returned by [get_superterm()]. Required when
#'   `superterms = TRUE`.
#' @param type Character. Which plot(s) to draw. One of:
#'   * `"clean"` : colored nodes, no labels.
#'   * `"superterms"` : colored nodes with community super-term labels.
#'   * `"combined"` : colored nodes with super-term labels and individual node
#'     labels.
#'   * `"individual"` : colored nodes with individual node labels only.
#'   * `"all"` : all four plots drawn sequentially. Default.
#' @param seed Integer. Random seed for the Fruchterman-Reingold layout and
#'   Louvain community detection. Default: `174`.
#'
#' @return Invisibly, a named list with:
#'   * `$graph`: The filtered `igraph` graph object (`g_clean`).
#'   * `$layout`: Numeric matrix with the normalized Fruchterman-Reingold node
#'     coordinates.
#'   * `$node_attributes`: A [tibble::tibble()] with columns `NAME`, `cluster`,
#'     `community`, `degree`, `betweenness`, and `closeness` (plus `superterm`
#'     if `superterms = TRUE`).
#'   * `$superterm_report`: A [tibble::tibble()] with columns `community`,
#'     `superterm`, `n_genesets`, and `geneset_members`. Only present if
#'     `superterms = TRUE`.
#'
#' @examples
#' \dontrun{
#' # Requires igraph
#' gsl <- list_gmts("path/to/gmt_folder/")
#' res <- read.csv("path/to/results.csv")
#'
#' jac   <- calc_jaccard(gsl, res, fdr_th = 0.05)
#' clust <- do_clust(jac)
#' net   <- get_network_communities(jac, threshold = 0.3)
#'
#' # Draw all four plots directly to the active graphics device
#' result <- network_clust(
#'   jac,
#'   clust_result   = clust,
#'   superterms     = TRUE,
#'   superterm_data = net$superterms,
#'   type           = "all",
#'   seed           = 174
#' )
#'
#' # Draw only the clean version (no labels)
#' network_clust(jac, clust, type = "clean")
#'
#' # Access node-level metrics from the invisible return
#' result$node_attributes
#' result$superterm_report
#'
#' # Save a specific plot to PDF
#' pdf("network_superterms.pdf", width = 14, height = 14)
#' network_clust(jac, clust, superterms = TRUE,
#'               superterm_data = net$superterms, type = "superterms")
#' dev.off()
#' }
#'
#' @seealso [calc_jaccard()], [do_clust()], [get_network_communities()],
#'   [get_superterm()], [network_clust_gg()]
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export

network_clust <- function(x, clust_result,
                          jaccard_threshold = 0.50,
                          min_degree        = 2,
                          superterms        = FALSE,
                          superterm_data    = NULL,
                          type              = "all",
                          seed              = 174) {

  if (!requireNamespace("igraph", quietly = TRUE)) {
    stop("Package \"igraph\" must be installed to use this function.", call. = FALSE)
  }

  # --- Input validation ---------------------------------------------------
  if (!inherits(x, "JaccardResult")) {
    stop(
      "`x` must be a `JaccardResult` object (output of `calc_jaccard()`).",
      call. = FALSE
    )
  }
  if (!is.list(clust_result) ||
      !all(c("cluster_assignments", "hclust") %in% names(clust_result))) {
    stop("`clust_result` must be the output of `do_clust()`.", call. = FALSE)
  }

  type <- match.arg(type, c("clean", "superterms", "combined", "individual", "all"))

  if (superterms && is.null(superterm_data)) {
    warning(
      "`superterms = TRUE` but no `superterm_data` was provided. ",
      "Run `get_superterm()` first and pass its output to `superterm_data`. ",
      "Falling back to `superterms = FALSE`.",
      call. = FALSE
    )
    superterms <- FALSE
  }

  if (superterms && type %in% c("clean", "individual")) {
    warning(
      "Super-term labels are not displayed for `type = \"", type, "\"`. ",
      "Use `type = \"superterms\"`, `\"combined\"`, or `\"all\"` to show them.",
      call. = FALSE
    )
  }

  # --- Build graph --------------------------------------------------------
  adj_mat               <- x$jaccard_sim
  adj_mat[adj_mat < jaccard_threshold] <- 0
  diag(adj_mat)         <- 0

  g       <- igraph::graph_from_adjacency_matrix(adj_mat, mode = "undirected", weighted = TRUE)
  g_clean <- igraph::induced_subgraph(g, igraph::V(g)[igraph::degree(g) > min_degree])

  if (igraph::vcount(g_clean) == 0) {
    stop(
      "No nodes remain after filtering. ",
      "Try lowering `jaccard_threshold` or `min_degree`.",
      call. = FALSE
    )
  }

  node_names <- igraph::V(g_clean)$name

  # --- Community detection ------------------------------------------------
  set.seed(seed)
  communities          <- igraph::cluster_louvain(g_clean)
  community_membership <- igraph::membership(communities)

  # --- Layout -------------------------------------------------------------
  set.seed(seed)
  layout_norm <- igraph::norm_coords(
    igraph::layout_with_fr(g_clean),
    xmin = -1, xmax = 1, ymin = -1, ymax = 1
  )

  # --- Node colors (from hierarchical clusters) ---------------------------
  node_clusters <- clust_result$cluster_assignments$cluster[
    match(node_names, clust_result$cluster_assignments$NAME)
  ]
  n_clusters  <- length(unique(stats::na.omit(node_clusters)))
  cluster_pal <- grDevices::rainbow(n_clusters, s = 0.7, v = 0.9)
  node_colors <- cluster_pal[as.factor(node_clusters)]

  # --- Super-term setup ---------------------------------------------------
  if (superterms) {
    st_mapping      <- superterm_data$mapping
    node_superterms <- st_mapping$superterm[match(node_names, st_mapping$geneset)]

    unique_comms <- sort(unique(community_membership))

    community_centroids <- do.call(rbind, lapply(unique_comms, function(cid) {
      idx <- which(community_membership == cid)
      if (length(idx) == 1L) layout_norm[idx, ]
      else colMeans(layout_norm[idx, , drop = FALSE])
    }))

    plot_labels <- vapply(unique_comms, function(cid) {
      lbl <- superterm_data$summary$superterm[superterm_data$summary$community == cid]
      if (length(lbl) == 0) NA_character_ else lbl[[1]]
    }, character(1))
  }

  # --- Internal plot helper -----------------------------------------------
  .draw_network <- function(show_labels      = FALSE,
                            label_cex        = 0.5,
                            superterm_overlay = FALSE,
                            main_title       = "Gene Set Network") {

    graphics::par(mar = c(1, 1, 3, 1))

    plot(
      g_clean,
      layout             = layout_norm,
      vertex.size        = if (show_labels) 5 else 6,
      vertex.color       = node_colors,
      vertex.label       = if (show_labels) node_names else NA,
      vertex.label.cex   = label_cex,
      vertex.label.color = "gray20",
      vertex.label.dist  = 0.3,
      vertex.frame.color = "gray30",
      vertex.frame.width = 0.5,
      edge.width         = igraph::E(g_clean)$weight * 3,
      edge.color         = grDevices::rgb(0.5, 0.5, 0.5, 0.3),
      main               = main_title,
      rescale            = FALSE,
      xlim               = c(-1.4, 1.4),
      ylim               = c(-1.4, 1.4),
      asp                = 0
    )

    if (superterm_overlay && superterms) {
      for (i in seq_along(unique_comms)) {
        lbl <- plot_labels[[i]]
        if (is.na(lbl)) next
        cx  <- community_centroids[i, 1]
        cy  <- community_centroids[i, 2]
        sw  <- graphics::strwidth(lbl,  cex = 1.2) * 1.3
        sh  <- graphics::strheight(lbl, cex = 1.2) * 2.5
        graphics::rect(
          cx - sw / 2, cy - sh / 2, cx + sw / 2, cy + sh / 2,
          col    = grDevices::rgb(1, 1, 1, 0.9),
          border = "gray40",
          lwd    = 1.5
        )
      }
      graphics::text(
        x      = community_centroids[, 1],
        y      = community_centroids[, 2],
        labels = plot_labels,
        cex    = 1.2,
        font   = 2,
        col    = "black"
      )
    }
  }

  # --- Draw requested plots -----------------------------------------------
  if (type %in% c("clean",      "all"))
    .draw_network(show_labels = FALSE, superterm_overlay = FALSE,
                  main_title  = "Gene Set Network - Clean")

  if (type %in% c("superterms", "all"))
    .draw_network(show_labels = FALSE, superterm_overlay = TRUE,
                  main_title  = "Gene Set Network - Super-terms")

  if (type %in% c("combined",   "all"))
    .draw_network(show_labels = TRUE,  label_cex = 0.4, superterm_overlay = TRUE,
                  main_title  = "Gene Set Network - Super-terms + Individual Labels")

  if (type %in% c("individual", "all"))
    .draw_network(show_labels = TRUE,  label_cex = 0.6, superterm_overlay = FALSE,
                  main_title  = "Gene Set Network - Individual Labels")

  # --- Node attributes ----------------------------------------------------
  node_attributes <- tibble::tibble(
    NAME        = node_names,
    cluster     = node_clusters,
    community   = as.integer(community_membership),
    degree      = igraph::degree(g_clean),
    betweenness = igraph::betweenness(g_clean),
    closeness   = igraph::closeness(g_clean)
  )

  if (superterms) node_attributes$superterm <- node_superterms

  # --- Build return object ------------------------------------------------
  result <- list(
    graph           = g_clean,
    layout          = layout_norm,
    node_attributes = node_attributes
  )

  if (superterms) {
    result$superterm_report <- superterm_data$mapping %>%
      dplyr::group_by(.data[["community"]], .data[["superterm"]]) %>%
      dplyr::summarise(
        n_genesets      = dplyr::n(),
        geneset_members = paste(.data[["geneset"]], collapse = " | "),
        .groups         = "drop"
      ) %>%
      dplyr::arrange(dplyr::desc(.data[["n_genesets"]]))
  }

  invisible(result)
}
##########################
# Function network_clust_gg #
##########################

#' Gene set network clustering with ggraph graphics
#'
#' Builds a weighted gene set network from a Jaccard similarity matrix, applies
#' Louvain community detection, and returns up to four ggplot2 network
#' visualizations using ggraph. Each plot is a standard ggplot2 object that
#' can be further customized, saved with [ggplot2::ggsave()], or combined
#' with patchwork.
#'
#' Optionally overlays super-term community labels generated by
#' [get_superterm()].
#'
#' For a base R igraph version that draws directly to the active graphics
#' device, see [network_clust()].
#'
#' @param x A `JaccardResult` object (output of [calc_jaccard()]).
#' @param clust_result A list returned by [do_clust()], used to color nodes by
#'   hierarchical cluster assignment.
#' @param jaccard_threshold Numeric. Minimum Jaccard similarity required for an
#'   edge to be included in the network. Default: `0.50`.
#' @param min_degree Integer. Minimum node degree for a node to be retained in
#'   the network. Default: `2`.
#' @param superterms Logical. If `TRUE`, overlays super-term labels at community
#'   centroids on the relevant plots. Requires `superterm_data`. Default:
#'   `FALSE`.
#' @param superterm_data A list returned by [get_network_communities()] (slot
#'   `$superterms`) or directly by [get_superterm()]. Required when
#'   `superterms = TRUE`.
#' @param type Character. Which plot(s) to return. One of:
#'   * `"clean"` : colored nodes, no labels.
#'   * `"superterms"` : colored nodes with community super-term labels.
#'   * `"combined"` : colored nodes with super-term labels and individual node
#'     labels.
#'   * `"individual"` : colored nodes with individual node labels only.
#'   * `"all"` : all four plots. Default.
#' @param seed Integer. Random seed for the Fruchterman-Reingold layout and
#'   Louvain community detection. Default: `174`.
#'
#' @return A named list. Depending on `type`, the list may contain any
#'   combination of the ggplot2 elements `$clean`, `$superterms`, `$combined`,
#'   and `$individual`. The list always contains:
#'   * `$node_attributes`: A [tibble::tibble()] with columns `NAME`, `cluster`,
#'     `community`, `degree`, `betweenness`, and `closeness` (plus `superterm`
#'     if `superterms = TRUE`).
#'   * `$superterm_report`: A [tibble::tibble()] with columns `community`,
#'     `superterm`, `n_genesets`, and `geneset_members`. Only present if
#'     `superterms = TRUE`.
#'
#' @examples
#' \dontrun{
#' # Requires igraph, ggraph, tidygraph
#' gsl <- list_gmts("path/to/gmt_folder/")
#' res <- read.csv("path/to/results.csv")
#'
#' jac   <- calc_jaccard(gsl, res, fdr_th = 0.05)
#' clust <- do_clust(jac)
#' net   <- get_network_communities(jac, threshold = 0.3)
#'
#' # Return all four plots as ggplot2 objects
#' plots <- network_clust_gg(
#'   jac,
#'   clust_result   = clust,
#'   superterms     = TRUE,
#'   superterm_data = net$superterms,
#'   type           = "all",
#'   seed           = 174
#' )
#'
#' # Display individual plots
#' plots$clean        # no labels
#' plots$superterms   # community labels only
#' plots$combined     # community + node labels
#' plots$individual   # node labels only
#'
#' # Save with ggsave (full ggplot2 objects)
#' ggplot2::ggsave("network_combined.pdf", plots$combined,
#'                 width = 14, height = 14)
#'
#' # Access node-level metrics
#' plots$node_attributes
#' plots$superterm_report
#'
#' # Combine two plots with patchwork
#' library(patchwork)
#' plots$clean + plots$superterms
#' }
#'
#' @seealso [calc_jaccard()], [do_clust()], [get_network_communities()],
#'   [get_superterm()], [network_clust()]
#' @import ggplot2
#' @importFrom magrittr %>%
#' @importFrom rlang .data
#' @export

network_clust_gg <- function(x, clust_result,
                             jaccard_threshold = 0.50,
                             min_degree        = 2,
                             superterms        = FALSE,
                             superterm_data    = NULL,
                             type              = "all",
                             seed              = 174) {

  if (!requireNamespace("igraph",    quietly = TRUE)) {
    stop("Package \"igraph\" must be installed to use this function.",    call. = FALSE)
  }
  if (!requireNamespace("ggraph",    quietly = TRUE)) {
    stop("Package \"ggraph\" must be installed to use this function.",    call. = FALSE)
  }
  if (!requireNamespace("tidygraph", quietly = TRUE)) {
    stop("Package \"tidygraph\" must be installed to use this function.", call. = FALSE)
  }

  # --- Input validation ---------------------------------------------------
  if (!inherits(x, "JaccardResult")) {
    stop(
      "`x` must be a `JaccardResult` object (output of `calc_jaccard()`).",
      call. = FALSE
    )
  }
  if (!is.list(clust_result) ||
      !all(c("cluster_assignments", "hclust") %in% names(clust_result))) {
    stop("`clust_result` must be the output of `do_clust()`.", call. = FALSE)
  }

  type <- match.arg(type, c("clean", "superterms", "combined", "individual", "all"))

  if (superterms && is.null(superterm_data)) {
    warning(
      "`superterms = TRUE` but no `superterm_data` was provided. ",
      "Run `get_superterm()` first and pass its output to `superterm_data`. ",
      "Falling back to `superterms = FALSE`.",
      call. = FALSE
    )
    superterms <- FALSE
  }

  if (superterms && type %in% c("clean", "individual")) {
    warning(
      "Super-term labels are not displayed for `type = \"", type, "\"`. ",
      "Use `type = \"superterms\"`, `\"combined\"`, or `\"all\"` to show them.",
      call. = FALSE
    )
  }

  # --- Build graph --------------------------------------------------------
  adj_mat               <- x$jaccard_sim
  adj_mat[adj_mat < jaccard_threshold] <- 0
  diag(adj_mat)         <- 0

  g       <- igraph::graph_from_adjacency_matrix(adj_mat, mode = "undirected", weighted = TRUE)
  g_clean <- igraph::induced_subgraph(g, igraph::V(g)[igraph::degree(g) > min_degree])

  if (igraph::vcount(g_clean) == 0) {
    stop(
      "No nodes remain after filtering. ",
      "Try lowering `jaccard_threshold` or `min_degree`.",
      call. = FALSE
    )
  }

  node_names <- igraph::V(g_clean)$name

  # --- Community detection ------------------------------------------------
  set.seed(seed)
  communities          <- igraph::cluster_louvain(g_clean)
  community_membership <- igraph::membership(communities)

  # --- Node colors --------------------------------------------------------
  node_clusters <- clust_result$cluster_assignments$cluster[
    match(node_names, clust_result$cluster_assignments$NAME)
  ]
  n_clusters  <- length(unique(stats::na.omit(node_clusters)))
  cluster_pal <- grDevices::rainbow(n_clusters, s = 0.7, v = 0.9)

  # --- Build tbl_graph with node metadata ---------------------------------
  tg <- tidygraph::as_tbl_graph(g_clean) %>%
    tidygraph::activate("nodes") %>%
    dplyr::mutate(
      cluster   = factor(node_clusters),
      community = as.integer(community_membership)
    )

  if (igraph::ecount(g_clean) > 0) {
    tg <- tg %>%
      tidygraph::activate("edges") %>%
      dplyr::mutate(weight = igraph::E(g_clean)$weight)
  }

  # --- Compute shared layout (FR) -----------------------------------------
  set.seed(seed)
  layout_obj <- ggraph::create_layout(tg, layout = "fr")

  # --- Community centroids for super-term labels --------------------------
  centroid_data   <- NULL
  node_superterms <- NULL

  if (superterms) {
    st_mapping      <- superterm_data$mapping
    node_superterms <- st_mapping$superterm[match(node_names, st_mapping$geneset)]

    centroid_data <- layout_obj %>%
      dplyr::mutate(community = as.integer(community_membership)) %>%
      dplyr::group_by(.data[["community"]]) %>%
      dplyr::summarise(
        x = mean(.data[["x"]]),
        y = mean(.data[["y"]]),
        .groups = "drop"
      ) %>%
      dplyr::left_join(
        superterm_data$summary %>%
          dplyr::select(.data[["community"]], .data[["superterm"]]),
        by = "community"
      )
  }

  # --- Internal ggraph plot builder ---------------------------------------
  .build_gg <- function(show_node_labels  = FALSE,
                        label_size        = 3,
                        show_superterms   = FALSE,
                        plot_title        = "Gene Set Network") {

    has_edges <- igraph::ecount(g_clean) > 0

    p <- ggraph::ggraph(layout_obj) +
      {if (has_edges)
        ggraph::geom_edge_link(
          ggplot2::aes(width = .data[["weight"]], alpha = .data[["weight"]]),
          color       = "gray50",
          show.legend = FALSE
        )} +
      ggraph::geom_node_point(
        ggplot2::aes(fill = .data[["cluster"]], color = .data[["cluster"]]),
        size        = 5,
        shape       = 21,
        stroke      = 0.5,
        show.legend = FALSE
      ) +
      ggraph::scale_edge_width(range = c(0.3, 2)) +
      ggraph::scale_edge_alpha(range = c(0.1, 0.5)) +
      ggplot2::scale_fill_manual(values  = cluster_pal, na.value = "gray80") +
      ggplot2::scale_color_manual(values = cluster_pal, na.value = "gray80") +
      ggplot2::labs(title = plot_title) +
      ggplot2::theme_void() +
      ggplot2::theme(
        plot.title  = ggplot2::element_text(size = 16, hjust = 0.5, face = "bold"),
        plot.margin = ggplot2::margin(10, 10, 10, 10)
      )

    if (show_node_labels) {
      p <- p + ggraph::geom_node_text(
        ggplot2::aes(label = .data[["name"]]),
        size  = label_size,
        repel = TRUE,
        color = "gray20"
      )
    }

    if (show_superterms && superterms && !is.null(centroid_data)) {
      p <- p +
        ggplot2::geom_label(
          data        = centroid_data,
          ggplot2::aes(
            x     = .data[["x"]],
            y     = .data[["y"]],
            label = .data[["superterm"]]
          ),
          size        = 4,
          fontface    = "bold",
          fill        = grDevices::rgb(1, 1, 1, 0.9),
          color       = "black",
          label.size  = 0.4,
          inherit.aes = FALSE
        )
    }

    return(p)
  }

  # --- Build requested plots ----------------------------------------------
  plots <- list()

  if (type %in% c("clean",      "all"))
    plots$clean <- .build_gg(
      show_node_labels = FALSE, show_superterms = FALSE,
      plot_title       = "Gene Set Network - Clean"
    )

  if (type %in% c("superterms", "all"))
    plots$superterms <- .build_gg(
      show_node_labels = FALSE, show_superterms = TRUE,
      plot_title       = "Gene Set Network - Super-terms"
    )

  if (type %in% c("combined",   "all"))
    plots$combined <- .build_gg(
      show_node_labels = TRUE,  label_size = 2.5, show_superterms = TRUE,
      plot_title       = "Gene Set Network - Super-terms + Individual Labels"
    )

  if (type %in% c("individual", "all"))
    plots$individual <- .build_gg(
      show_node_labels = TRUE, label_size = 3, show_superterms = FALSE,
      plot_title       = "Gene Set Network - Individual Labels"
    )

  # --- Node attributes ----------------------------------------------------
  node_attributes <- tibble::tibble(
    NAME        = node_names,
    cluster     = node_clusters,
    community   = as.integer(community_membership),
    degree      = igraph::degree(g_clean),
    betweenness = igraph::betweenness(g_clean),
    closeness   = igraph::closeness(g_clean)
  )

  if (superterms) node_attributes$superterm <- node_superterms

  plots$node_attributes <- node_attributes

  # --- Superterm report ---------------------------------------------------
  if (superterms) {
    plots$superterm_report <- superterm_data$mapping %>%
      dplyr::group_by(.data[["community"]], .data[["superterm"]]) %>%
      dplyr::summarise(
        n_genesets      = dplyr::n(),
        geneset_members = paste(.data[["geneset"]], collapse = " | "),
        .groups         = "drop"
      ) %>%
      dplyr::arrange(dplyr::desc(.data[["n_genesets"]]))
  }

  return(plots)
}
