#' GDC TCGA Lung Adenocarcinoma (LUAD) - Raw STAR counts
#'
#' A subset of TCGA-LUAD RNA-seq gene-level counts generated by STAR and distributed via UCSC Xena.
#' Data originate from GDC, only selected samples are included.
#' Gene identifiers are Ensembl IDs with the version suffix removed (e.g., "ENSG00000141510.15" → "ENSG00000141510").
#' Sample barcodes were compacted and written with dots instead of dashes (e.g., "TCGA-38-4627-11A" → "TCGA.38.4627.11A").
#'
#' @format ## `raw_counts`
#' A data frame with 60,660 rows and 32 columns:
#' \describe{
#'   \item{rownames}{Ensembl gene IDs (GRCh38) with version suffix stripped (no ".##").}
#'   \item{columns}{TCGA sample IDs written with dots instead of dashes, e.g., `TCGA.38.4627.11A`.}
#'   \item{values}{Integer raw counts from STAR gene quantification (untransformed).}
#' }
#' @source <https://gdc-hub.s3.us-east-1.amazonaws.com/download/TCGA-LUAD.star_counts.tsv.gz>
"raw_counts"
